---
# Common variables
cluster_subnet: "192.168.20.0/24"
vip: "192.168.20.150"
interface: "eth0"
rke2_token: "mysupersecretcattletoken"
metallb_range: "192.168.20.200-192.168.20.220"

# Rancher configuration
rancher_hostname: "rancher.fedora.solutions"
letsencrypt_email: "support@fedoratechnologies.net"
