---
collections:
  - name: ansible.posix
    version: 1.5.1
  - name: kubernetes.core
    version: 2.4.0
  - name: cloud.common
    version: 2.1.3
  - name: community.crypto
    version: 2.17.0
  - name: community.general
    version: 6.8.3