---
- name: Install MetalLB
  kubernetes.core.k8s:
    state: present
    src: https://raw.githubusercontent.com/metallb/metallb/v0.13.7/config/manifests/metallb-native.yaml

- name: Apply MetalLB configuration
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'metallb-config.yaml.j2') | from_yaml }}"

- name: Install cert-manager
  kubernetes.core.k8s:
    state: present
    src: https://github.com/cert-manager/cert-manager/releases/download/v1.13.1/cert-manager.yaml

- name: Add Rancher Helm repo
  community.helm.helm_repository:
    name: rancher-latest
    repo_url: https://releases.rancher.com/server-charts/latest

- name: Install Rancher
  community.helm.helm:
    name: rancher
    chart_ref: rancher-latest/rancher
    namespace: cattle-system
    release_values:
      hostname: "{{ rancher_hostname }}"
      bootstrapPassword: admin
      ingress:
        tls:
          source: letsEncrypt
      letsEncrypt:
        email: "{{ letsencrypt_email }}"
    create_namespace: true
